DROP TABLE IF EXISTS ADDRESSES;
CREATE TABLE ADDRESSES (ID INT AUTO_INCREMENT PRIMARY KEY,
STREET VARCHAR(100) NOT NULL,
NUMBER INT  NOT NULL,
LOCATION VARCHAR(100) NOT NULL,
PROVINCE VARCHAR(100) NOT NULL);

DROP TABLE IF EXISTS PATIENT;
CREATE TABLE PATIENT (ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
CARD_IDENTITY INT NOT NULL,
ADMISSION_OF_DATE DATE NOT NULL,
ADDRESS_ID INT NOT NULL);

DROP TABLE IF EXISTS DENTIST;
CREATE TABLE DENTIST (ID INT AUTO_INCREMENT PRIMARY KEY,
REGISTRATION INT NOT NULL,
NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL);

INSERT INTO ADDRESSES (STREET, NUMBER, LOCATION, PROVINCE) VALUES ('Calle A', 101, 'Laboulaye', 'Córdoba');
INSERT INTO PATIENT (NAME, LAST_NAME, EMAIL, CARD_IDENTITY, ADMISSION_OF_DATE, ADDRESS_ID) VALUES('Marina', 'Revol', 'mnrevol50@gmail.com', 35258777, '2025-11-30',1);
INSERT INTO DENTIST (REGISTRATION, NAME, LAST_NAME) VALUES(1234, 'Juan', 'Muela');
